---
- hosts: local
  connection: local
  gather_facts: no
  vars:
      zone: example.com
      record: home.example.com

  tasks:
      - name: Get Dynamic IP address
        uri: 
            url: http://api.jasonmurray.org/ip 
            return_contents: yes
        register: json_response

      - name: Update Dynamic DNS in AWS
        route53:
            state: present
            zone: "{{ zone }}"
            record: "{{ record }}"
            type: A
            ttl: 300
            value: "{{ json_response.json.ip }}"
            wait: yes

      - name: debug
        debug:
            var: json_response.json.ip 

